### PR TITLE
MANIFEST.in: Add requirements.txt

### PR DESCRIPTION
**Pull request by jayvdb**
requirements.txt is needed by setup.py

### CODE REVIEW

**Comment by MaxvanderWeide** [comment]
Hey @jayvdb, thanks for contributing!
Could you add a brief explanation as to why `requirements.txt` needs to be added to the MANIFEST? We already read the requirements in [setup.py](https://github.com/vwt-digital/openapi3-fuzzer/blob/develop/setup.py#L5).

**Comment by MaxvanderWeide** [comment]
Closing due to inactivity. Please leave a comment if there is anything to add!

**Comment by jayvdb** [comment]
> We already read the requirements in setup.py.

@MaxvanderWeide , that is precisely the problem.

The `requirements.txt` isnt in the sdist uploaded to PyPI.  setup.py fails because of this.  It cant find the file which exists in the repo, but not in the tarball.  To experience this, you need to fetch the sdist from PyPI and use its setup.py.

**Comment by MaxvanderWeide** [comment]
@jayvdb looks fine to me: `writing requirements to openapi3_fuzzer.egg-info/requires.txt`. 
Can you share the setup's output when it fails? Maybe we have some differences in how it is uploaded.

**Comment by jayvdb** [comment]
> @jayvdb looks fine to me: `writing requirements to openapi3_fuzzer.egg-info/requires.txt`.
> Can you share the setup's output when it fails? Maybe we have some differences in how it is uploaded.

That line is irrelevant.  I repeat: To experience this bug, you need to fetch the sdist from PyPI and use its setup.py.  There is no requirements.txt (not require.txt in the egg-info subdir) in the sdist.

**Comment by MaxvanderWeide** [comment]
Released with [1.3.1](https://pypi.org/project/openapi3-fuzzer/1.3.1/)

**Pull request merged**
